config/routes.rb
Rails.application.routes.draw do

  devise_for :customers, skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

devise_for :admin, skip: [:registrations, :passwords], controllers: {
  sessions: "admin/sessions"
}

root to: "public/homes#top"


  namespace :admin do
    get 'homes/top' => 'homes#top'
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show]
  end

  namespace :public do
    root to: "homes#top"
    get 'homes/about' => 'homes#about'

    # get 'customers/my_page' => 'customers#show'
    get 'customers/information/unsubscribe' => 'customers#unsubscribe'
    get 'customers/information/withdraw' => 'customers#withdraw'
    # get 'customers/information' => 'customers#update'
    # get 'customers/information/edit' => 'customers#edit'
    delete '/cart_items/destroy_all' => 'cart_items#destroy_all', as: 'destroy_all_cart_items'

    post 'orders/confirm' => 'orders#confirm'
    get 'orders/complete' => 'orders#complete'

    resources :items, only: [:index, :show]
    resources :customers, only: [:show, :edit, :update, :unsubscribe, :withdraw]
    resources :cart_items, only: [:index, :update, :destroy, :create]
    resources :orders, only: [:new, :confirm, :complete, :create, :index, :show]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image
  has_many :cart_items, dependent: :destroy
  # has_many :orders, through: :cart_items
  has_many :order_details, dependent: :destroy

  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image
  end

  def with_tax_price
    (price * 1.1).floor
  end

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController

  def new
    @item = Item.new
  end

  def create

    @item = Item.new(item_params)
    if @item.save
      flash[:notice] = "You have created item successfully."
      redirect_to admin_item_path(@item)
    else @items = Item.all
      render :index
    end
  end

  def index
    @items = Item.all
    @item = Item.new
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit

    # item = .find(params[:id])
    # unless book.user_id == current_user.id
    # redirect_to books_path
    # end

    @item = Item.find(params[:id])
  end

  def update

    # item = Item.find(params[:id])
    # unless book.user_id == current_user.id
    #   redirect_to books_path
    # end

    @item = Item.find(params[:id])
      if @item.update(item_params)
        flash[:notice] = "You have updated item successfully."
        redirect_to admin_items_path(@item)
      else
        render :edit
      end
  end

  def destroy
    item = Item.find(params[:id])
    item.destroy
    redirect_to admin_items_path
  end



  private

  def item_params
    params.require(:item).permit(:image, :name, :introduction, :price)
  end

end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/views/admin/items/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h4>商品編集</h4>

      <% if @item.errors.any? %>
        <%= @item.errors.count %>errors prohibited this item from being saved:
        <ul>
          <% @item.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      <% end %>

      <%= form_with model: @item, url: admin_item_path(@item.id), method: :patch do |f| %>

        <div class="form-grop mt-2">
           <h6>商品画像</h6>
            <%= f.file_field :image, accept: "image/*" %>
        </div>

        <div class="form-grop mt-2">
          <h6>商品名</h6>
          <%= f.text_field :name, class: "form-control item_name" %>
        </div>

        <div class="form-grop mt-2">
          <h6>商品説明</h6>
          <%= f.text_area :introduction, class: "form-control admin_item_introduction" %>
        </div>

        <div class="form-grop mt-2">
          <h6>税抜価格</h6>
          <%= f.text_field :price, class: "form-control admin_item_introduction" %>
        </div>

        <div class="form-grop mt-2">
          <%= f.submit '変更を保存', class: "btn btn-success" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/items/index.html.erb
<h4>商品一覧</h4>
<p><%= link_to "新規登録", new_admin_item_path %></p>

<table>
  <thead>
    <tr>
      <th>商品ID</th>
      <th>商品名</th>
      <th>税抜価格</th>
      <th></th>
    </tr>
  </thead>

　<tbody>
  <% @items.each do |item| %>
    <tr>
      <td><%= item.id %></td>
      <!--<td>-->
      <!--  <% if item.image.attached? %>-->
      <!--    <%= image_tag item.image, size: "100x100" %>-->
      <!--  <% else %>-->
      <!--    <%= image_tag 'no_image', size: "100x100" %>-->
      <!--  <% end %>-->
      <!--</td>-->
      <td>
        <%= link_to admin_item_path(item.id) do %>
        <%= item.name %>
        <% end %>
        </td>
      <td><%= item.price %></td>
    <!--  <td><%= link_to "Edit", edit_admin_item_path(item.id) %></td>-->
    <!--  <td><%= link_to "Destroy", admin_item_path(item.id), method: :delete, "data-confirm" => "Are you sure" %></td>-->
    <!--</tr>-->
  <% end %>
  </tbody>
</table>

app/views/admin/items/new.html.erb
<h4>商品新規登録</h4>

<% if @item.errors.any? %>
  <%= @item.errors.count %>件のエラーが発生しました
  <ul>
    <% @item.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with model: @item, url: '/admin/items',  method: :post do |f| %>
  <h6>商品画像</h6>
  <%= f.file_field :image, accept: "image/*" %>
  <h6>商品名</h6>
  <%= f.text_field :name %>
  <h6>商品説明</h6>
  <%= f.text_area :introduction %>
  <h6>価格</h6>
  <%= f.text_field :price %>
  <%= f.submit '新規登録' %>
<% end %>

app/views/admin/items/show.html.erb
<div class='col-md-8 offset-md-1'>
    <h4>商品詳細</h4>
  <table class='table table-hover table-inverse'>
    <%= image_tag @item.get_image, size: "100x100" %>
    <tbody>
      <thead>
        <tr>
          <th>商品名</th>
          <th>商品説明</th>
          <th>税抜価格（税込価格）</th>
          <th></th>
        </tr>
      </thead>
      <tr>
        <td>
          <%= link_to admin_item_path(@item.id) do %>
            <%= @item.name %>
          <% end %>
        </td>
        <td>
          <%= @item.introduction %>
        </td>
        <td>
          <%= @item.price %> (<%= @item.with_tax_price %>)
        </td>

        <td>
          <%= link_to "編集", edit_admin_item_path(@item.id), class: "btn btn-sm btn-success" %>
        </td>

      </tr>
    </tbody>
  </table>
  </div>
  </div>
</div>