config/routes.rb
Rails.application.routes.draw do

  devise_for :customers, skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

devise_for :admin, skip: [:registrations, :passwords], controllers: {
  sessions: "admin/sessions"
}

root to: "public/homes#top"


  namespace :admin do
    get 'homes/top' => 'homes#top'
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show]
  end

  namespace :public do
    root to: "homes#top"
    get 'homes/about' => 'homes#about'

    # get 'customers/my_page' => 'customers#show'
    get 'customers/information/unsubscribe' => 'customers#unsubscribe'
    get 'customers/information/withdraw' => 'customers#withdraw'
    # get 'customers/information' => 'customers#update'
    # get 'customers/information/edit' => 'customers#edit'
    delete '/cart_items/destroy_all' => 'cart_items#destroy_all', as: 'destroy_all_cart_items'

    post 'orders/confirm' => 'orders#confirm'
    get 'orders/complete' => 'orders#complete'

    resources :items, only: [:index, :show]
    resources :customers, only: [:show, :edit, :update, :unsubscribe, :withdraw]
    resources :cart_items, only: [:index, :update, :destroy, :create]
    resources :orders, only: [:new, :confirm, :complete, :create, :index, :show]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items, foreign_key: :customer_id, dependent: :destroy
  has_many :orders, dependent: :destroy

    def full_name
    "#{first_name} #{last_name}"
    end

    def full_name_kana
    "#{first_name_kana} #{last_name_kana}"
    end

    def addresses
      '〒' + postal_code + ' ' + address + ' ' + full_name
    end

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController

  def index
    @customer = Customer.all
  end

  def show
    @customers = Customer.find(params[:id])
  end

  def edit
      @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
      if @customer.update(customer_params)
        flash[:notice] = "You have updated user successfully."
        redirect_to admin_customer_path(@customer.id)
      else
        render :edit
      end
  end

  private

  def customer_params
    params.require(:customer).permit(:first_name, :last_name, :first_name_kana, :last_name_kana, :postal_code, :address, :telephone_number, :customer_email)
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h4>登録情報編集</h4>

      <%= form_with model: @customer, url: admin_customer_path(@customer.id), method: :patch do |f| %>

        <div class="form-grop mt-3">
          <h6>会員ID</h6>
          <%= @customer.id %>
        </div>

        <div class="field">
    <h6>名前</h6>
    <%= f.label :"（性）" %>
    <%= f.text_field :first_name, autofocus: true, autocomplete: "name" %>
    <br/><%= f.label :"（名）" %>
    <%= f.text_field :last_name, autofocus: true, autocomplete: "name" %>
  </div>

  <div class="field">
    <h6>フリガナ</h6>
    <%= f.label :"（セイ）" %>
    <%= f.text_field :first_name_kana, autofocus: true, autocomplete: "name" %>
    <br/><%= f.label :"（メイ） "%>
    <%= f.text_field :last_name_kana, autofocus: true, autocomplete: "name" %>
  </div>

  <div class="field">
    <h6>郵便番号（ハイフンなし）</h6>
    <%= f.text_field :postal_code, autofocus: true, autocomplete: "postal_code" %>
  </div>

  <div class="field">
    <h6>住所</h6>
    <%= f.text_field :address, autofocus: true, autocomplete: "address" %>
  </div>

  <div class="field">
    <h6>電話番号（ハイフンなし）</h6>
    <%= f.text_field :telephone_number, autofocus: true, autocomplete: "telephone_number" %>
  </div>

  <div class="field">
    <h6>メールアドレス</h6>
    <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
  </div>


        <div class="form-grop mt-3">
          <%= f.submit '更新', class: "btn btn-secondary" %>
        </div>
      <% end %>




    </div>
  </div>
</div>

app/views/admin/customers/index.html.erb
<div class='col-md-8 offset-md-1'>
    <h2>顧客一覧</h2>
  <table class='table table-hover table-inverse'>
    <thead>
      <tr>
        <th>会員ID</th>
        <th>氏名</th>
        <th>メールアドレス</th>
        <th>ステータス</th>
      </tr>
    </thead>
    <tbody>
     <% @customer.each do |customer| %>
      <tr>
        <td>
          <%= customer.id %>
        </td>
        <td>
          <%= link_to admin_customer_path(customer.id) do %>
            <%= customer.full_name %>
          <% end %>
        </td>
        <td>
          <%= customer.email %>
        </td>
        <td>
          <%= customer.is_active ? "有効" : "無効" %>
        </td>
      </tr>
     <% end %>
    </tbody>
  </table>
  </div>

app/views/admin/customers/show.html.erb
<h4>会員詳細</h4>

  <table class='table'>
    <thead>
      <tr>
        <th>会員ID</th>
        <th>氏名</th>
        <th>フリガナ</th>
        <th>郵便番号</th>
        <th>住所</th>
        <th>電話番号</th>
        <th>メールアドレス</th>
        <th>会員ステータス</th>
      </tr>
    </thead>
    <tbody>
      <% customer = @customers %>
        <tr>
          <td>
          <%= customer.id %>
          </td>
          <td>
          <%= customer.full_name %>
          </td>
          <td>
          <%= customer.full_name_kana %>
          </td>
          <td>
          <%= customer.postal_code %>
          </td>
          <td>
          <%= customer.address %>
          </td>
          <td>
          <%= customer.telephone_number %>
          </td>
          <td>
          <%= customer.email %>
          </td>
          <td>
            <%= customer.is_active ? "有効" : "無効" %>
          </td>
        </tr
    </tbody>
  </table>


  <div>
    <h5>登録情報</h5>
    <%= link_to "編集する", edit_admin_customer_path %>
  </div>
  <div>
    <h5>注文履歴</h5>
    <%= link_to "一覧を見る", public_orders_path %>
  </div>