config/routes.rb
Rails.application.routes.draw do

  devise_for :customers, skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

devise_for :admin, skip: [:registrations, :passwords], controllers: {
  sessions: "admin/sessions"
}

root to: "public/homes#top"


  namespace :admin do
    get 'homes/top' => 'homes#top'
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show]
  end

  namespace :public do
    root to: "homes#top"
    get 'homes/about' => 'homes#about'

    # get 'customers/my_page' => 'customers#show'
    get 'customers/information/unsubscribe' => 'customers#unsubscribe'
    get 'customers/information/withdraw' => 'customers#withdraw'
    # get 'customers/information' => 'customers#update'
    # get 'customers/information/edit' => 'customers#edit'
    delete '/cart_items/destroy_all' => 'cart_items#destroy_all', as: 'destroy_all_cart_items'

    post 'orders/confirm' => 'orders#confirm'
    get 'orders/complete' => 'orders#complete'

    resources :items, only: [:index, :show]
    resources :customers, only: [:show, :edit, :update, :unsubscribe, :withdraw]
    resources :cart_items, only: [:index, :update, :destroy, :create]
    resources :orders, only: [:new, :confirm, :complete, :create, :index, :show]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <header>
      <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
        <a class="navbar-brand" >
        <%= link_to "Logo", public_root_path %>
        </a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <% if admin_signed_in? %>
                <li class="nav-item">
                  <%= link_to "商品一覧", admin_items_path %>
                </li>
                <li class="nav-item">
                  <%= link_to "会員一覧", admin_customers_path %>
                </li>
                <li class="nav-item">
                  <%= link_to "注文履歴一覧", admin_homes_top_path %>
                </li>
                <li class="nav-item">
                  <%= link_to "ログアウト", destroy_admin_session_path, method: :delete %>
                </li>
              <% elsif customer_signed_in? %>
                <li class="nav-item">
                  <%= link_to "マイページ", public_customer_path(current_customer) %>
                </li>
                <li class="nav-item">
                  <%= link_to "商品一覧", public_items_path %>
                </li>
                <li class="nav-item">
                  <%= link_to "カート",  public_cart_items_path %>
                </li>
                <li class="nav-item">
                  <%= link_to "ログアウト", destroy_customer_session_path, method: :delete %>
                </li>
              <% else %>
                <li class="nav-item">
                  <%= link_to "About", public_homes_about_path %>
                </li>
                <li class="nav-item">
                  <%= link_to "商品一覧", public_items_path %>
                </li>
                <li class="nav-item">
                  <%= link_to "新規登録", new_customer_registration_path %>
                </li>
                <li class="nav-item">
                  <%= link_to "ログイン", customer_session_path %>
                </li>
              <% end %>
            </ul>
            <!--<form class="d-flex" role="search">-->
            <!--  <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">-->
            <!--  <button class="btn btn-outline-success" type="submit">Search</button>-->
            <!--</form>-->
          </div>
        </div>
      </nav>
    </header>

    <%= yield %>
  </body>
</html>